- PROJECT-PLAN.md
- rainspub/DESIGN.md
Probably I need to move some parts to the design section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/1)
> First draft of the project plan. 

- .gitignore
- rainsd/engine.go
- rainsd/inbox.go
- rainsd/serverInfo.go
- rainsd/serverUtil.go
- rainsd/verify.go
- rainsdig/rainsdig.go
- rainslib/datamodel.go
- rainslib/rainslibUtil.go
- utils/cache/cache.go
- utils/cache/cache_test.go
- utils/parser/rainsMsgParser.go
- utils/set/set.go
- utils/set/set_test.go
Concurrency safe set data structure, refactoring go routine calls
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/7)
> Concurrency safe set data structure

- Makefile
- integration/main.go
- integration/utils/utils.go
- rainsd/cache.go
- rainsd/serverInfo.go
- rainsd/serverInfo_test.go
- rainsd/serverInterfaceImpl.go
@fehlmach This should revert the assertion cache to be an interface again, and fix the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/90)
> Revert assertion cache changes

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/115)
> Update makefile to use new paths

- internal/pkg/cache/pendingKeyCache.go
- internal/pkg/cache/pendingQueryCache.go
Fixes a bug in the pending cache where it was possible to add an arbitrary amount of entries into the cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/148)
> Pending cache counter bug fix

- internal/pkg/cache/cache_test.go
- internal/pkg/cache/pendingKeyCache_test.go
- internal/pkg/cache/pendingQueryCache_test.go
Adds unit tests to the pending key cache and pending query cache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/149)
> Pending caches unit tests

- docs/components-overview.md
This document describes the tools used in the RAINS ecosystem and refers to other documentation to get a more detailed view of each tool.
The different actors in a RAINS environment are mentioned and which tools are most useful for them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/166)
> RAINS components documentation

- .circleci/config.yml
- .gitignore
- cmd/rainsdig/DESIGN.md
- cmd/rdig/rdig.go
- docs/man/rdig.md
- internal/pkg/object/object.go
- internal/pkg/query/query.go
This PR updates the man page of rdig and the implementation to match the updated RAINS draft.
Each query option can be set by an individual flag.
Fixes #177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/176)
> Rains dig man page and implementation update

- cmd/rdig/rdig.go
Complete nonce -> token renaming from PR #176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/184)
> Fix flag handling

- .circleci/config.yml
- cmd/rainsd/rainsd.go
- internal/pkg/connection/connection.go
- internal/pkg/libresolve/resolver.go
- internal/pkg/rainsd/inbox.go
Change SCION integration repo
Add missing flags
Busy wait fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/189)
> Prepare deployment

- test/integration/README.md
Closes #185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/190)
> Integration Test Documentation

- cmd/rainsd/rainsd.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/196)
> stores flag content to local variable in rainsd

- cmd/rainsd/rainsd.go
- internal/pkg/libresolve/resolver.go
- internal/pkg/libresolve/resolver_test.go
- internal/pkg/rainsd/queryEngine.go
- internal/pkg/rainsd/server.go
- internal/pkg/section/assertion.go
- internal/pkg/section/assertion_test.go
- internal/pkg/section/testData.go
- internal/pkg/util/rainslibUtil.go
- internal/pkg/util/rainslibUtil_test.go
- test/integration/fullCoverageTCP.go
- test/integration/fullCoverageTCP_test.go
Closes #119 
Needs UT and integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/170)
> 119 check signatures in rlookup

- internal/pkg/cache/connectionCache.go
- internal/pkg/cache/interfaces.go
- internal/pkg/object/object.go
- internal/pkg/rainsd/server.go
- internal/pkg/rainsd/switchboard.go
- test/integration/fullCoverageTCP_test.go
* Run integration test through the CLI tools
* Close connections on server Shutdown
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/198)
> Add integration test for the CLI tools

- internal/pkg/libresolve/resolver.go
- internal/pkg/libresolve/resolver_test.go
Review the approach
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/212)
> Added two UTs to libresolve

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/218)
> Update circleci image

- internal/pkg/connection/connection.go
Fixes a bug where setting up a connection would panic when snet.DefNetwork is nil.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/219)
> Fix panic on nil snet.DefNetwork

- .circleci/config.yml
- test/integration/fullCoverageTCP_test.go
Run integration tests using SCION built from source using bazel
Do not depend on outdated base image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/230)
> Fixup integration

- cmd/rainsd/rainsd.go
- cmd/rdig/rdig.go
- cmd/zonepub/zonepub.go
- go.mod
- go.sum
- internal/pkg/connection/connection.go
- internal/pkg/connection/scion/appnet.go
- internal/pkg/connection/scion/path_selection.go
- internal/pkg/libresolve/resolver.go
- internal/pkg/object/object.go
- internal/pkg/rainsd/switchboard.go
- test/integration/fullCoverageSCION_test.go
Update to last version before monolith, replace `snet.Addr` with `snet.UDPAddr`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/233)
> Update scion, remove snet.Addr

- .circleci/config.yml
- go.mod
- go.sum
- internal/pkg/connection/scion/appnet.go
- test/integration/fullCoverageSCION_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/234)
> Adapt lib and integration tests to sciond over TCP

- .circleci/config.yml
- go.mod
- go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/rains/236)
> Bump SCION to v0.5.0
